### ISSUE TITLE
Use Map for more efficient representation?

### ISSUE THREAD

**Issue by dylex** [phadej/range-set-list#4]
Rather than an ordered list of ranges, what if you had
```
newtype RSet a = Data.Map.Strict.Map a a
```
Where the keys are the lower-bounds and the values are the upper-bounds. Then, with liberal use of `Map.lookupLE` you could greatly improve the time complexity of many operations.  I haven't found any other implementations that do this, and would be happy to work it into a PR if it seems like a good idea.  (There could even be a specialized IntMap version for the probably most common case.)

**Comment by dylex** [comment]
I guess on the down side you'd probably have to change the name of the package (and add a containers dependency)...

**Comment by phadej** [comment]
This is good idea. I'd rather not add it to this package though, but make a new one. This one could be used as a testing dependency, if needed. That was the original plan (make a binary tree implementation), but I found that list based implementation was good enough for my applications (usually few but very wide ranges).

If you want to do the package, I'd glad to help and review if needed. I'd name it `discrete-range-set`, as there are use cases for more general range sets, i.e. over dense values (for example `RangeSet` over ` Version`). In that case you have to distinguish between open and closed boundaries.

**Comment by dylex** [comment]
Seems reasonable, and yeah, the existing `range` package (and some others) seem to have covered the more general case.  I'll probably fork your code if I do this as you have a good API and test cases that would still apply.  Thanks.

You might want to fix the category in your cabal file, btw.

**Comment by phadej** [comment]
Thanks for `range` and cabal mistake pointers
